### ISSUE TITLE
Support for dates in JsonSchema

### ISSUE THREAD

**Issue by stefanholzmueller** [endpoints4s/endpoints4s#233]
Should be pretty easy to implement `JsonSchema[java.time.LocalDate]`, but that's not everything.
In OpenAPI specifications I'd expect a schema like `{ "type": "string", "format": "date" }`.

It seems impossible for the user to define a schema with a custom format, but we could add schemas for well-known types. The comments in https://github.com/julienrf/endpoints/pull/136 suggest exactly that. I'd say `java.time` is not third-party and could be added right away.

Other types (like `OffsetDateTime`) could be added as well, but I'm not so sure which ones make sense. I only stumbled upon `LocalDate` because I use it in a REST service.

**Comment by julienrf** [comment]
> It seems impossible for the user to define a schema with a custom format

It is possible, users can always create a trait extending the `JsonSchemas` algebra and defining an abstract method `dateJsonSchema: JsonSchema[Date]`, and then implement this method in a trait extending a `JsonSchemas` interpreter.

> I'd say `java.time` is not third-party and could be added right away.

Yes but the problem is that this package exists only on Java 8, meaning that we would not anymore support older versions of Java. I’m not sure if this is a big problem, though.

**Comment by stefanholzmueller** [comment]
I'm still surprised how extensible *endpoints* is. :) You're right, I will just create my own trait.

And I wrongly assumed that older versions of Java are not supported anymore, so nevermind. Doesn't make sense to drop support for such a tiny issue.

If you have the same opinion, feel free to close this issue.

**Comment by julienrf** [comment]
We can keep the issue open as it would be cool to have out of the box support for dates, at some point :)
