### ISSUE TITLE
genericJsonSchema doesn't support Set

### ISSUE THREAD

**Issue by marconilanna** [endpoints4s/endpoints4s#682]
The following code compiles:

```scala
final case class A (
  a: String,
  b: Seq[Int]
)

final implicit lazy val aSchema: JsonSchema[A] = genericJsonSchema
```

The following doesn't:

```scala
final case class B (
  a: String,
  b: Set[Int]
)

final implicit lazy val bSchema: JsonSchema[B] = genericJsonSchema
```

```
Unable to derive an instance of JsonSchema[B].
The type B must be a sealed trait or a case class.
f it is a sealed trait, make sure it is only extended by case classes and that a JsonSchema can be derived for each of these case classes (see hereafter).
If it is a case class, make sure each field of the case class has an implicit JsonSchema.
You can check that a JsonSchema is available for a type T by compiling the expression `implicitly[JsonSchema[T]]`.
```

**Comment by julienrf** [comment]
A workaround is to define your own JSON schema for `Set`:

~~~ scala
implicit def setJsonSchema[A: JsonSchema]: JsonSchema[Set[A]] =
  implicitly[JsonSchema[List[A]].xmap(_.toSet)(_.toList)
~~~

But the reason why it doesn’t work is because `arrayJsonSchema` requires the collection type constructor to be a `Seq` (see [API docs](https://endpoints4s.github.io/api/endpoints4s/algebra/JsonSchemas.html#arrayJsonSchema[C[X]%3C:Seq[X],A](implicitjsonSchema:JsonSchemas.this.JsonSchema[A],implicitfactory:collection.compat.Factory[A,C[A]]):JsonSchemas.this.JsonSchema[C[A]])). Maybe we could relax this constraint and accept any `Iterable`? :thinking:
